version: '3.8'

services:
  db:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: 3W_cda
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
